version: '3'

services:
  client:
    build: client/
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/mydatabase
  server:
    build: server/
    ports:
      - "3000:3000"