version: '3'

services:
  server:
    build: server/
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/mydatabase
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app