version: '3'

services:
  client:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/mydatabase
  server:
    build: ./server/
    ports:
      - "8000:8000"