version: '3'

services:
  web:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./original_data.json:/app/original_data.json
      - ./updated_data.json:/app/updated_data.json
    environment:
      - OPENAI_API_KEY=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